Support Modern Remote Chrome
Icinga/icingaweb2-module-pdfexport pull request #71
Opened 2024-07-01 20:25 UTC by srvrguy

Starting in version 66, Chrome DevTools requires the host header to be “localhost” or an IP address. Work around this by setting the header to “lcoalhost” when fetching the version endpoint.

2024-07-01 20:34 UTC, srvrguy commented
This particular issue has been a problem since Chrome version 66 in 2018 when a change was made to improve security on DevTools. If you're using a local install, you won't run into the issue. I'm guessing most users of this module are configured in this manner.

The problem surfaces when using a container version of icingaweb2. Unless you make a custom container, the official one doesn't include Chrome installed. The best solution is to spin up a container running a headless version of Chrome. While you can get around the issue by putting in an IP address, this may change across container restarts. Especially under Kubernetes, you will want to use the friendly DNS name to fix this.

This small patch works around the security issue by forcing the host header to "localhost" when fetching the version endpoint. With that set, the expected values are returned and can be used by the rest of the module.

2024-07-25 08:43 UTC, nilmerg commented
Hi, thank your for pointing this out! However, since this is a case specific to containerized setups, I think it is safer to first try a normal request. (without spoofing the host header) If this fails with the error `Host header is specified and is not an IP address or localhost.`, your suggested solution can safely be performed.

2024-11-21 22:33 UTC, srvrguy commented
The updated PR now handles the issue in a different way. Since Guzzle emits an exception on a 5xx error, I've wrapped the first request in a try block and am only catching the specific error thrown when getting the security error message. Inside the catch, I just have the request try again without a Host header. It's a big larger of a change than I would have liked, but does the job just fine.

2024-11-25 09:39 UTC, nilmerg requested changes
Thanks! Though, phpcs complains, please have a look :)

2024-11-25 09:39 UTC, nilmerg commented on library/Pdfexport/HeadlessChrome.php
> +                    ['headers' => ['Host' => null]]);
```suggestion
                $response = $client->request(
                    'GET',
                    sprintf('http://%s:%s/json/version', $host, $port),
                    ['headers' => ['Host' => null]]
                );
```

2024-11-26 00:15 UTC, srvrguy commented
> Thanks! Though, phpcs complains, please have a look :)

Simple formatting issue that shouldn't take long to fix this week. Do you want me to add as a separate commit, or should I amend and force push to keep the history clean?

2024-11-26 07:50 UTC, nilmerg commented
You can commit my suggestion directly here. I'll squash afterwards.

2024-11-27 11:21 UTC, nilmerg approved these changes
LGTM!

2024-11-27 11:21 UTC, merged